### ISSUE TITLE
installation issues and doc.records.serialize() gives empty output

### ISSUE THREAD

**Issue by ViktorWeissenborn** [CambridgeMolecularEngineering/chemdataextractor2#12]
Hey,

i had some trouble installing the CDE2 package via pip inside a clean conda environment (i tried python versions from 3.7 to 3.9 without any difference). Also i tried the CDE2 installation on win terminal, powershell, wsl and on an ubuntu 20.04 system terminal, without any difference. The errorLogs were quite huge, i put them here as file attatchment. In general the installation always errored out while installing build dependencies for spacy 2.1.9.

Eventually i tried some fixes from stackoverflow...

https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci
https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit
https://github.com/explosion/spaCy#pip

...and used 'venv' instead of 'conda' and I got an installation without errors. The -V flag shows the version 2.1.1 and its possible to import it into python (as seen below). But using doc.records.serialize() gives an empty output neither for a normal sentence nor for a organic chemistry paper html-file, even though the allenNLP model got loaded correctly (as seen below).

caffeine@caffeine-ThinkPad-E590:~$ source .env/bin/activate
(.env) caffeine@caffeine-ThinkPad-E590:~$ cde -V
cde, version 2.1.1
(.env) caffeine@caffeine-ThinkPad-E590:~$ python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chemdataextractor import Document
>>> import chemdataextractor
>>> chemdataextractor.__version__
'2.1.1'
>>> from chemdataextractor import Document
>>> doc = Document('xy was extracted using ethanol.')
>>> doc.records.serialize()
Initialising AllenNLP model ✔
[]
>>> f = open('/home/caffeine/Desktop/test/01_acs-jnatprod-5b00099.html', 'rb')
>>> doc = Document.from_file(f)
>>> doc.records.serialize()
[]
>>>

So for me in general it would be very helpful if u could tell me exactly how u installed the chemdataextractor2 package to see if there might be something i forgot or got wrong during the installation process. Also if u have any idea how i could fix my current installation (problem with "doc.records.serialize()") i would be very grateful. But a detailed description of how u installed CDE2 would be of my greatest help right now, because i guess all of this could be resolved by just a correct, clean reinstallation.

greetings
Viktor

[ErrorLog_CDE2_installation_botocore.txt](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/files/8388533/ErrorLog_CDE2_installation_botocore.txt)
[ErrorLog_CDE2_installation.txt](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/files/8388535/ErrorLog_CDE2_installation.txt)
[ErrorLog_CDE2_withUpdatedSetuptoolsInNonCondaEnv.txt](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/files/8388536/ErrorLog_CDE2_withUpdatedSetuptoolsInNonCondaEnv.txt)

**Comment by ti250** [comment]
Hi Viktor,

To get records you need to set the document to look for compounds, so in your case, adding the following lines should help:

```
from chemdataextractor.model import Compound
doc.models = [Compound]
```

With regards to the errors, it seems to me like pip couldn't find gcc or some suitable C compiler which is needed to use one of the libraries (a patched version of DAWG) on Python 3.7 and above, not sure why using venv fixed this though...

**Comment by ViktorWeissenborn** [comment]
Hey, thanks a lot for the quick answer!

Your suggestions helped me, and it does indeed look for compounds now.

I have two more questions now:

First: With "doc.models = [Compound]" CDE lets look me only for "Compounds" without further annotated properties, lables, whatever. Is there a way to look for every annotation regarding a found compound CDE can find? For example in CDE1.3 you could just use "...records.serialize()" and CDE checked for every compound plus every belonging annotation (like lable, biological property, category, etc).

Second: I still would like to install CDE2.1.1 to a conda env. After a pip install of chemdataextractor2 i get the following error when trying to call the version with 'cde -V' or importing the module Document in python:

```
(CDE2fix) caffeine@caffeine-ThinkPad-E590:~$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chemdataextractor import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/__init__.py", line 26, in <module>
    from .doc.document import Document
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/doc/__init__.py", line 15, in <module>
    from .document import Document
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/doc/document.py", line 24, in <module>
    from .text import Paragraph, Citation, Footnote, Heading, Title
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/doc/text.py", line 21, in <module>
    from ..model import ModelList
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/model/__init__.py", line 12, in <module>
    from .base import BaseType, StringType, FloatType, ModelType, ListType, BaseModel, ModelList, InferredProperty
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/model/base.py", line 22, in <module>
    from ..parse.elements import Any, W, I
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/parse/__init__.py", line 20, in <module>
    from .cem import CompoundParser, ChemicalLabelParser, CompoundHeadingParser
  File "/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/parse/cem.py", line 18, in <module>
    from ..model import Compound
ImportError: cannot import name 'Compound' from partially initialized module 'chemdataextractor.model' (most likely due to a circular import) (/home/caffeine/.local/lib/python3.8/site-packages/chemdataextractor/model/__init__.py)
```

Maybe u have run into it, too, and have some workaround for it.

greetings
Viktor Weißenborn
