### ISSUE TITLE
Check_records 

### ISSUE THREAD

**Issue by jghasemi44** [CambridgeMolecularEngineering/chemdataextractor2#55]
I used the first version cde but after installation of cde-2 I faced some errors like check_records is not a module or submodule. Please let me know how can I tackle this issue.

**Comment by Dingyun-Huang** [comment]
Please post your code snippet and exception traceback so that we could reproduce your situation.

**Comment by Dingyun-Huang** [comment]
Hi there,

I am sorry that you are experiencing some problems migrating from CDE1 to CDE2, but I could not reproduce your error on my laptop. I would suggest create a new fresh environment and re-run the installation using pip install.

```
conda create -n env_name python=3.7
conda activate env_name
pip install chemdataextractor2
```

If you still experience some problems please post again.

Best wishes,
Dingyun

**Comment by sparrowcolab** [comment]
Dear Dingyun,

Before I wrote my previous comment, I tried 

conda create -n env_name python=3.7
conda activate env_name
pip install chemdataextractor2, 

several times, with python=3.6, 3.6, 3.8, always the problem about the urllib3 and ssl exists and confilicting dependcies as six, click and requests versions appeared several times,
by downgrading and cleaning cach I managed to get the CDE2 working, the main problem now is now at 
d.records.serialize, when it starts to inisialize the BERT in chemdataextractor.nlp.allenenlp, it  gives the following error:
 
File "C:\Amg\envs\ide_env\lib\gzip.py", line 493, in read
raise EOFError("Compressed file ended before the "

EOFError: Compressed file ended before the end-of-stream marker was reached,

I'm new to GIT, so if you tell me how I can help you to reproduce the problem, I can give you more helpful data,

Finally, thank you for trying to help,

Best Regards,
sparrow

**Comment by Dingyun-Huang** [comment]
Hi Sparrow,

Can you run `cde data download` and re-try your programme?

**Comment by sparrowcolab** [comment]
Dear Dingyun,

I tried to run cde data download at the conda CMD console, but got stuck at the following message: 
Couldn't find models/bert_finetuned_crf_model-1.0a, downloading...
Couldn't find models/scibert_cased_weights-1.0.tar.gz, downloading...,
Then after period of time, got the following message:
Successfully downloaded 0 new data packages (22 existing)

but I tried to run my CDE2, and fourtanatly this time when I ran: 
for record in doc.records:
    res = record.serialize

The AllenNLP initialized and started to run for bit more seconds untill I get the following error: 
itialising AllenNLP model .  Automatically activating GPU support
Initialising AllenNLP model ...✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✘ Couldn't link model to 'en_core_web_sm'
Creating a symlink in spacy/data failed. Make sure you have the required
permissions and try re-running the command as admin, or use a virtualenv. You
can still import the model as a module and call its load() method, or create the
symlink manually.
C:\Amg\envs\ide_env\lib\site-packages\en_core_web_sm -->
C:\Amg\envs\ide_env\lib\site-packages\spacy\data\en_core_web_sm
[?25hTraceback (most recent call last):

  File "C:\Amg\envs\ide_env\lib\site-packages\allennlp\common\util.py", line 289, in get_spacy_model
    spacy_model = spacy.load(spacy_model_name, disable=disable)

  File "C:\Amg\envs\ide_env\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)

  File "C:\Amg\envs\ide_env\lib\site-packages\spacy\util.py", line 139, in load_model
    raise IOError(Errors.E050.format(name=name))

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Amgad Ahmed\AppData\Local\Temp\ipykernel_8584\3059345307.py", line 1, in <module>
    for record in doc.records:

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\document.py", line 276, in records
    element_definitions = el.definitions

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 360, in definitions
    return [definition for sent in self.sentences for definition in sent.definitions]

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 360, in <listcomp>
    return [definition for sent in self.sentences for definition in sent.definitions]

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\utils.py", line 29, in fget_memoized
    setattr(self, attr_name, fget(self))

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 771, in definitions
    for result in self.specifier_definition.scan(tokens):

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 117, in scan
    results, next_i = self.parse(tokens, i)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 146, in parse
    result, found_index = self._parse_tokens(tokens, i, actions)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 427, in _parse_tokens
    exprresults, i = e.parse(tokens, i)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 146, in parse
    result, found_index = self._parse_tokens(tokens, i, actions)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 656, in _parse_tokens
    results, i = self.expr.parse(tokens, i, actions)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 146, in parse
    result, found_index = self._parse_tokens(tokens, i, actions)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 551, in _parse_tokens
    result, result_i = e.parse(tokens, i, actions=True)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 146, in parse
    result, found_index = self._parse_tokens(tokens, i, actions)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\parse\elements.py", line 297, in _parse_tokens
    tag = token[self.tag_type]

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 1220, in __getitem__
    return self.legacy_pos_tag

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 1210, in legacy_pos_tag
    ner_tag = self[NER_TAG_TYPE]

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 1222, in __getitem__
    return self.__getattr__(key)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 1230, in __getattr__
    self.sentence._assign_tags(name)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\text.py", line 832, in _assign_tags
    self.document._batch_assign_tags(tagger, tag_type)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\document.py", line 718, in _batch_assign_tags
    tag_results = tagger.batch_tag_for_type(all_tokens, tag_type)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\nlp\tag.py", line 206, in batch_tag_for_type
    return tagger.batch_tag(sents)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\nlp\allennlpwrapper.py", line 194, in batch_tag
    batch_predictions = self.predictor.predict_batch_instance(instance)

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\nlp\allennlpwrapper.py", line 158, in predictor
    self._predictor = copy.deepcopy(SentenceTaggerPredictor(model=model, dataset_reader=None))

  File "C:\Amg\envs\ide_env\lib\site-packages\allennlp\predictors\sentence_tagger.py", line 26, in __init__
    self._tokenizer = SpacyWordSplitter(language=language, pos_tags=True)

  File "C:\Amg\envs\ide_env\lib\site-packages\allennlp\data\tokenizers\word_splitter.py", line 173, in __init__
    self.spacy = get_spacy_model(language, pos_tags, parse, ner)

  File "C:\Amg\envs\ide_env\lib\site-packages\allennlp\common\util.py", line 302, in get_spacy_model
    link(spacy_model_name, spacy_model_name, model_path=package_path)

  File "C:\Amg\envs\ide_env\lib\site-packages\spacy\cli\link.py", line 65, in link
    symlink_to(link_path, model_path)

  File "C:\Amg\envs\ide_env\lib\site-packages\spacy\compat.py", line 96, in symlink_to
    ["mklink", "/d", path2str(orig), path2str(dest)], shell=True

  File "C:\Amg\envs\ide_env\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['mklink', '/d', 'C:\\Amg\\envs\\ide_env\\lib\\site-packages\\spacy\\data\\en_core_web_sm', 'C:\\Amg\\envs\\ide_env\\lib\\site-packages\\en_core_web_sm']' returned non-zero exit status 1.,

I belive some lib are missing but I don't know how I can get it installed, and no matter, how many times i tried to reinstall CDE2 even in different machines, it didn't go further from todays results

**Comment by sparrowcolab** [comment]
I then managed to download the en_core_web_sm==2.1.0, from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.

Then when reached: 
   
doc.models = [CurrentDensity]) 
the GPU was automatically activated as follows:
itialising AllenNLP model .  Automatically activating GPU support
itialising AllenNLP model ✔ ...
and CDE2 keep running for about 4 mins with GPU utilization ranging between 40 to 100%, and then got the following error message:

doc.models = [CurrentDensity]
itialising AllenNLP model .  Automatically activating GPU support
itialising AllenNLP model ✔ ...
Traceback (most recent call last):

  File "C:\Users\Amgad Ahmed\AppData\Local\Temp\ipykernel_8584\4033503847.py", line 8, in <module>
    for record in doc.records:

  File "C:\Amg\envs\ide_env\lib\site-packages\chemdataextractor\doc\document.py", line 393, in records
    for contextual_record in contextual_records:

NameError: name 'contextual_records' is not defined

**Comment by Dingyun-Huang** [comment]
Hi there,

There isn't an active line of `for contextual_record in contextual_records` in `document.py` in the source code. You can check the source code file [here](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/blob/master/chemdataextractor/doc/document.py).

If you have edited the source code, please try revert that change. If you haven't, then run `pip show chemdataextractor2` in your conda environment and note the version of CDE2. The newest version is 2.3.2.

Best,
Dingyun

**Comment by sparrowcolab** [comment]
Hi, 
I think the problem is partially solved, CDE2 now is running without triggring erro messages, although the outcome results are not same as CDE1 in terms of etracted data,
when you suggested to run cde data download, I got the message that files don't exist, when I checkd the pages mannually , I found 404 error page can't found, then I manually searched for the crf_bert, and other missing files and installed it manually and it worked.

Concerning the contextual records, you are correct, I corrected some modificationes I did to the source code and everything is apparently running well,

Thank you so much for your help,
I might seek your help again if any new issues poped up,

Best regards,
Sparrow
