### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by qhm1000** [CambridgeMolecularEngineering/chemdataextractor2#61]
EOFError: Compressed file ended before the end-of-stream marker was reached
I found this error and could not figure out the reason.

**Comment by Dingyun-Huang** [comment]
Hi there, we need more details to know what you are trying to do. Could you please post your code and output here?

**Comment by tian685** [comment]
doc = Document(Heading('Properties of caffeine (1)'),
              Paragraph('Lorem ipsum dolor sit amet. We also determined the glass transition temperature of caffeine, Tg = 123.4°C'))
print(doc)
print(doc.records)

Errors:
 Traceback (most recent call last):
  File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/demo.py", line 11, in <module>
    print(doc.records)
  File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/doc/document.py", line 248, in records
    element_definitions = el.definitions
  File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/doc/text.py", line 353, in definitions
    return [definition for sent in self.sentences for definition in sent.definitions]
  File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/doc/text.py", line 353, in <listcomp>
    return [definition for sent in self.sentences for definition in sent.definitions]
  File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/utils.py", line 29, in fget_memoized
    setattr(self, attr_name, fget(self))
 .....
 ....
 File "/opt/miniconda3/envs/chemdata/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/opt/miniconda3/envs/chemdata/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/miniconda3/envs/chemdata/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by tian685** [comment]
> Hi there, we need more details to know what you are trying to do. Could you please post your code and output here?

doc = Document(Heading('Properties of caffeine (1)'),
Paragraph('Lorem ipsum dolor sit amet. We also determined the glass transition temperature of caffeine, Tg = 123.4°C'))
print(doc)
print(doc.records)

Errors:
Traceback (most recent call last):
File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/demo.py", line 11, in
print(doc.records)
File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/doc/document.py", line 248, in records
element_definitions = el.definitions
File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/doc/text.py", line 353, in definitions
return [definition for sent in self.sentences for definition in sent.definitions]
File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/doc/text.py", line 353, in
return [definition for sent in self.sentences for definition in sent.definitions]
File "/home/lxb24/OpenChemie/chemdataextractorTADF/tests/chemdataextractor/utils.py", line 29, in fget_memoized
setattr(self, attr_name, fget(self))
.....
....
File "/opt/miniconda3/envs/chemdata/lib/python3.6/gzip.py", line 276, in read
return self._buffer.read(size)
File "/opt/miniconda3/envs/chemdata/lib/python3.6/_compression.py", line 68, in readinto
data = self.read(len(byte_view))
File "/opt/miniconda3/envs/chemdata/lib/python3.6/gzip.py", line 482, in read
raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by Dingyun-Huang** [comment]
Can you run `cde data where` to check where are the CDE models installed and post what models are there? The folder path should be something like `/home/username/.local/share/ChemDataExtractor/models`.

**Comment by tian685** [comment]
> Can you run `cde data where` to check where are the CDE models installed and post what models are there? The folder path should be something like `/home/username/.local/share/ChemDataExtractor/models`.

您好，我是在root用户下重新用python3.7安装的chemdataextractor2，安装成功了，但是运行example notebook时，输出跟以下cde data where的报错结果一致 。我在哔哩哔哩中看了安装视频，评论中提到了输出的以下错误，但是我把vpn转为全局模式，也是一样的错误。
(Chem2dataset) (base) root@master:/home/lxb24/OpenChemie# cde data where
输出：
Downloading stanza due to error HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stanfordnlp/stanza-en/resolve/v1.6.0/models/tokenize/combined.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f1036c390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f1036c390>: Failed to establish a new connection: [Errno 101] Network is unreachable
......
......
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/nlp/dependency.py", line 66, in DependencyTagger
    taggers = [_DependencyTagger(), IndexTagger()]
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/nlp/dependency.py", line 31, in __init__
    stanza.download("en", resources_version="1.1.0")
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 588, in download
    md5=resources[lang]['default_md5'],
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 154, in request_file
    assert_file_exists(path, md5, alternate_md5)
  File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 107, in assert_file_exists
    raise ValueError("md5 for %s is %s, expected %s" % (path, file_md5, md5))
ValueError: md5 for /root/stanza_resources/en/default.zip is 1195812a37c01a4481a4748c85d0c6a9, expected 1a421b02f6a1a061197dfce6dacd26cd

**Comment by tian685** [comment]
> Can you run `cde data where` to check where are the CDE models installed and post what models are there? The folder path should be something like `/home/username/.local/share/ChemDataExtractor/models`.
我在root/username/.local/share/ChemDataExtractor/models里面找到了模型，但是为什么还要下载一些md5 for /root/stanza_resources/en/default.zip，好奇怪哦！
