### ISSUE TITLE
ValueError: md5 for /root/stanza_resources/en/default.zip is 1195812a37c01a4481a4748c85d0c6a9, expected 1a421b02f6a1a061197dfce6dacd26cd

### ISSUE THREAD

**Issue by tian685** [CambridgeMolecularEngineering/chemdataextractor2#66]
python=3.7，cde2安装成功，但是运行example notebooks时好像在下载一些东西log.txt：
 INFO       in modeling.py         --> Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
INFO       in modeling_bert.py    --> Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
INFO       in modeling_xlnet.py   --> Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
INFO       in registrable.py      --> instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
INFO       in registrable.py      --> instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
INFO       in registrable.py      --> instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
INFO       in registrable.py      --> instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
INFO       in tokenization.py     --> loading vocabulary file /root/.local/share/ChemDataExtractor/models/scibert_cased_vocab-1.0.txt
 
开了全局代理，仍然错误，如下：

Downloading stanza due to error HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stanfordnlp/stanza-en/resolve/v1.6.0/models/tokenize/combined.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f99db524e90>: Failed to establish a new connection: [Errno 101] Network is unreachable')) Traceback (most recent call last): File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection raise err File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection sock.connect(sa) OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request self._validate_conn(conn) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn conn.connect() File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect conn = self._new_conn() File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn self, "Failed to establish a new connection: %s" % e) urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f99db524e90>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/requests/adapters.py", line 449, in send timeout=timeout File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen _stacktrace=sys.exc_info()[2]) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stanfordnlp/stanza-en/resolve/v1.6.0/models/tokenize/combined.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f99db524e90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/nlp/dependency.py", line 28, in init self._nlp = stanza.Pipeline("en", tokenize_pretokenized=True, logging_level="ERROR") File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/pipeline/core.py", line 251, in init log_info=False) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 531, in download_models alternate_md5=resources[lang][key][value].get('alternate_md5', None) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 152, in request_file download_file(url, temppath, proxies, raise_for_status) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 114, in download_file r = requests.get(url, stream=True, proxies=proxies) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/requests/api.py", line 75, in get return request('get', url, params=params, **kwargs) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/requests/api.py", line 60, in request return session.request(method=method, url=url, **kwargs) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stanfordnlp/stanza-en/resolve/v1.6.0/models/tokenize/combined.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f99db524e90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/home/lxb24/test/demo.py", line 6, in from chemdataextractor.doc import Document File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/init.py", line 25, in from .doc.document import Document File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/doc/init.py", line 12, in from .document import Document File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/doc/document.py", line 24, in from .text import Paragraph, Citation, Footnote, Heading, Title, Caption, RichToken, Sentence, Cell File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/doc/text.py", line 31, in from ..nlp.dependency import DependencyTagger, IndexTagger File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/nlp/dependency.py", line 65, in class DependencyTagger(EnsembleTagger): File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/nlp/dependency.py", line 66, in DependencyTagger taggers = [_DependencyTagger(), IndexTagger()] File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/chemdataextractor/nlp/dependency.py", line 31, in init stanza.download("en", resources_version="1.1.0") File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 588, in download md5=resources[lang]['default_md5'], File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", line 154, in request_file assert_file_exists(path, md5, alternate_md5) File "/opt/miniconda3/envs/Chem2dataset/lib/python3.7/site-packages/stanza/resources/common.py", 
line 107, in assert_file_exists raise ValueError("md5 for %s is %s, expected %s" % (path, file_md5, md5)) ValueError: md5 for /root/stanza_resources/en/default.zip is 1195812a37c01a4481a4748c85d0c6a9, expected 1a421b02f6a1a061197dfce6dacd26cd

**Comment by Dingyun-Huang** [comment]
Hi there, this looks like a connection issue when downloading resources for the stanza package, which is managed by Stanford NLP. Unfortunately, we are not able to fix this as it is not a bug with CDE2. Please refer to https://stanfordnlp.github.io/stanza/download_models.html#automatic-download for downloading stanza resources.
